[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "random-number"
version = "0.0.1"
description = ""
dependencies = []

[project.scripts]
rn = "random_number:cli"